# Code Generated by Sidekick is for learning and experimentation purposes only.
import json
import re
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple


# ========== CONFIG ==========
INPUT_DIR = Path("./combined-apps")      # <-- main folder containing subfolders (native/saml/service/spa/web/...)
OUTPUT_DIR = Path("./out_tfvars")

SAML_OUT = OUTPUT_DIR / "saml_data.tfvars"
OAUTH_OUT = OUTPUT_DIR / "oauth_data.tfvars"
# ============================


def get_path(obj: Any, path: str, default: Any = None) -> Any:
    cur = obj
    for part in path.split("."):
        m = re.fullmatch(r"([^{{{{\[\]]+)(\[(\d+)\]}}}})?", part)
        if not m:
            return default
        key = m.group(1)
        idx = m.group(3)

        if not isinstance(cur, dict) or key not in cur:
            return default
        cur = cur[key]

        if idx is not None:
            if not isinstance(cur, list):
                return default
            i = int(idx)
            if i < 0 or i >= len(cur):
                return default
            cur = cur[i]
    return cur


def to_tf_key(label: str) -> str:
    s = (label or "").strip()
    if not s:
        s = "UNNAMED_APP"
    s = s.upper()
    s = re.sub(r"[^A-Z0-9_]+", "_", s)
    s = re.sub(r"_+", "_", s).strip("_")
    if not s:
        s = "UNNAMED_APP"
    if re.match(r"^\d", s):
        s = f"APP_{s}"
    return s


def dedupe_key(key: str, used: set) -> str:
    if key not in used:
        used.add(key)
        return key
    n = 2
    while f"{key}_{n}" in used:
        n += 1
    key2 = f"{key}_{n}"
    used.add(key2)
    return key2


def hcl_escape_string(s: str) -> str:
    return (
        s.replace("\\", "\\\\")
         .replace('"', '\\"')
         .replace("\n", "\\n")
         .replace("\r", "\\r")
         .replace("\t", "\\t")
    )


def to_hcl(value: Any, indent: int = 0, step: int = 2) -> str:
    sp = " " * indent
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, str):
        return f"\"{hcl_escape_string(value)}\""
    if isinstance(value, list):
        if not value:
            return "[]"
        inner = ",\n".join(f"{' ' * (indent + step)}{to_hcl(v, indent + step, step)}" for v in value)
        return "[\n" + inner + "\n" + sp + "]"
    if isinstance(value, dict):
        if not value:
            return "{}"
        lines = []
        for k, v in value.items():
            lines.append(f"{' ' * (indent + step)}{k} = {to_hcl(v, indent + step, step)}")
        return "{\n" + "\n".join(lines) + "\n" + sp + "}"
    raise TypeError(f"Unsupported type: {type(value)}")


def extract_saml_app(doc: Dict[str, Any]) -> Tuple[str, Dict[str, Any]]:
    label = get_path(doc, "application.label", "") or ""
    key = to_tf_key(label)

    signon = get_path(doc, "application.settings.signOn", {}) or {}
    app = {
        "label": label or None,
        "sso_acs_url": signon.get("ssoAcsUrl"),
        "recipient": signon.get("recipient"),
        "destination": signon.get("destination"),
        "audience": signon.get("audience"),
        "idp_issuer": signon.get("idpIssuer"),
        "subject_name_id_template": signon.get("subjectNameIdTemplate"),
        "subject_name_id_format": signon.get("subjectNameIdFormat"),
        "response_signed": signon.get("responseSigned"),
        "assertion_signed": signon.get("assertionSigned"),
        "signature_algorithm": signon.get("signatureAlgorithm"),
        "digest_algorithm": signon.get("digestAlgorithm"),
        "honor_force_authn": signon.get("honorForceAuthn"),
        "authn_context_class_ref": signon.get("authnContextClassRef"),
        "attribute_statements": signon.get("attributeStatements") if isinstance(signon.get("attributeStatements"), list) else [],
    }
    return key, app


def extract_oidc_app(doc: Dict[str, Any]) -> Tuple[str, Dict[str, Any]]:
    label = get_path(doc, "application.label", "") or ""
    key = to_tf_key(label)

    oauth_settings = get_path(doc, "application.settings.oauthClient", {}) or {}
    oauth_creds = get_path(doc, "application.credentials.oauthClient", {}) or {}
    auth0 = get_path(doc, "authorizationServers[0]", {}) or {}

    app = {
        "label": label or None,
        "application_type": oauth_settings.get("application_type"),
        "grant_types": oauth_settings.get("grant_types") if isinstance(oauth_settings.get("grant_types"), list) else [],
        "response_types": oauth_settings.get("response_types") if isinstance(oauth_settings.get("response_types"), list) else [],
        "redirect_uris": oauth_settings.get("redirect_uris") if isinstance(oauth_settings.get("redirect_uris"), list) else [],
        "post_logout_redirect_uris": oauth_settings.get("post_logout_redirect_uris") if isinstance(oauth_settings.get("post_logout_redirect_uris"), list) else [],
        "consent_method": oauth_settings.get("consent_method"),
        "issuer_mode": oauth_settings.get("issuer_mode"),
        "refresh_token_rotation": get_path(doc, "application.settings.oauthClient.refresh_token.rotation_type", None),
        "token_endpoint_auth_method": oauth_creds.get("token_endpoint_auth_method"),
        "authserver_name": get_path(auth0, "server.name", None),
        "auth_policy_name": get_path(auth0, "policy.name", None),
        "auth_policy_rule_name": get_path(auth0, "rules[0].name", None),
        "auth_grant_type_whitelist": get_path(auth0, "rules[0].conditions.grantTypes.include", []) or [],
    }
    return key, app


def write_tfvars_map(var_name: str, entries: Dict[str, Dict[str, Any]], out_path: Path) -> None:
    lines: List[str] = [f"{var_name} = {{"]
    for k, v in entries.items():
        lines.append(f"  {k} = {to_hcl(v, indent=2)}")
    lines.append("}")
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    saml_apps: Dict[str, Dict[str, Any]] = {}
    oidc_apps: Dict[str, Dict[str, Any]] = {}
    used_saml_keys, used_oidc_keys = set(), set()

    # Recursive scan through all subfolders
    json_files = sorted([p for p in INPUT_DIR.rglob("*.json") if p.is_file()])
    if not json_files:
        raise SystemExit(f"No .json files found under: {INPUT_DIR.resolve()}")

    for p in json_files:
        try:
            doc = json.loads(p.read_text(encoding="utf-8"))
        except Exception as e:
            print(f"[WARN] Skipping unreadable JSON: {p} ({e})")
            continue

        mode = get_path(doc, "application.signOnMode", None)
        if mode == "SAML_2_0":
            k, app = extract_saml_app(doc)
            k = dedupe_key(k, used_saml_keys)
            saml_apps[k] = app
        elif mode == "OPENID_CONNECT":
            k, app = extract_oidc_app(doc)
            k = dedupe_key(k, used_oidc_keys)
            oidc_apps[k] = app
        else:
            print(f"[WARN] Skipping {p}: unsupported signOnMode={mode!r}")

    write_tfvars_map("saml_apps", saml_apps, SAML_OUT)
    write_tfvars_map("oidc_apps", oidc_apps, OAUTH_OUT)

    print(f"[OK] Read {len(json_files)} JSON files under {INPUT_DIR.resolve()}")
    print(f"[OK] Wrote {len(saml_apps)} SAML apps -> {SAML_OUT.resolve()}")
    print(f"[OK] Wrote {len(oidc_apps)} OIDC apps -> {OAUTH_OUT.resolve()}")


if __name__ == "__main__":
    main()
